USE SUCOS;

/*INCLUINDO DADOS NA TABELA*/
/*FOI USADO O SCRIPT AUXILIAR*/
SELECT * FROM tbclientes;

SELECT CPF, NOME, ENDERECO1, BAIRRO, CIDADE, IDADE, SEXO FROM TBCLIENTES;

SELECT CPF, NOME FROM TBCLIENTES;

SELECT CPF, NOME FROM TBCLIENTES LIMIT 5;

SELECT CPF AS CPF_CLIENTE, NOME AS NOME_CLIENTE FROM TBCLIENTES;

/*FILTRANDO REGISTROS*/
SELECT * FROM tbprodutos;

SELECT * FROM TBPRODUTOS WHERE PRODUTO = '544931';

SELECT * FROM tbclientes WHERE CIDADE = 'Rio de Janeiro';

SELECT * FROM tbprodutos WHERE SABOR = 'Limão'; /*MUDOU O SABOR PARA CÍTRICOS*/

UPDATE tbprodutos SET SABOR = 'Cítricos' WHERE SABOR = 'Limão';

SELECT * FROM TBPRODUTOS WHERE SABOR = 'Cítricos';

/*FILTRANDO USANDO [MAIOR >] [MENOR <] E [DIFERENTE <>]*/
SELECT * FROM  TBCLIENTES;

SELECT * FROM TBCLIENTES WHERE IDADE = 22;
 
SELECT * FROM TBCLIENTES WHERE IDADE > 22;
 
SELECT * FROM TBCLIENTES WHERE IDADE < 22; 

SELECT * FROM TBCLIENTES WHERE IDADE <= 22; 

SELECT * FROM TBCLIENTES WHERE IDADE >= 22; 

SELECT * FROM TBCLIENTES WHERE IDADE <> 22;

SELECT * FROM TBCLIENTES WHERE NOME > 'Fernando Cavalcante';
 
SELECT * FROM TBCLIENTES WHERE NOME >= 'Fernando Cavalcante'; 

SELECT * FROM TBCLIENTES WHERE NOME <> 'Fernando Cavalcante'; 

SELECT * FROM TBPRODUTOS WHERE PRECO_LISTA = 16.008; /*VAI DAR ERRADO PQ É FLOAT*/

SELECT * FROM TBPRODUTOS WHERE PRECO_LISTA > 16.008;

SELECT * FROM TBPRODUTOS WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009;

/*FILTRANDO DATAS*/
SELECT * FROM TBCLIENTES;

SELECT * FROM TBCLIENTES WHERE DATA_NASCIMENTO = '1995-01-13';

SELECT * FROM TBCLIENTES WHERE DATA_NASCIMENTO > '1995-01-13';

SELECT * FROM TBCLIENTES WHERE DATA_NASCIMENTO <= '1995-01-13';

SELECT * FROM TBCLIENTES WHERE DATA_NASCIMENTO <> '1995-01-13';

SELECT * FROM TBCLIENTES WHERE YEAR(DATA_NASCIMENTO) = 1995; 

SELECT * FROM TBCLIENTES WHERE MONTH(DATA_NASCIMENTO) = 1995; 

/*FILTROS COMPOSTOS*/
SELECT * FROM TBPRODUTOS WHERE PRECO_LISTA >= 16.007 AND PRECO_LISTA <= 16.009;

SELECT * FROM TBCLIENTES WHERE IDADE >= 18 AND IDADE <= 22;

SELECT * FROM TBCLIENTES WHERE IDADE >= 18 AND IDADE <= 22 AND SEXO = 'M';

SELECT * FROM TBCLIENTES WHERE CIDADE = 'Rio de Janeiro' OR BAIRRO = 'Jardins';

SELECT * FROM TBCLIENTES WHERE (IDADE >= 18 AND IDADE <= 22 AND SEXO = 'M') 
OR (CIDADE = 'Rio de Janeiro' OR BAIRRO = 'Jardins');

