/*CRIAÇÃO COM SCRIPTS DE RECUPERAÇÃO*/
CREATE DATABASE SUCOS_VENDAS;
USE SUCOS_VENDAS;

/*REVISANDO CONSULTAS*/
SELECT CPF, NOME, ENDERECO_1, ENDERECO_2, BAIRRO, CIDADE,
ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, SEXO, LIMITE_DE_CREDITO,
VOLUME_DE_COMPRA, PRIMEIRA_COMPRA FROM TABELA_DE_CLIENTES;

SELECT * FROM tabela_de_clientes;

SELECT CPF, NOME FROM tabela_de_clientes;

SELECT CPF AS IDENTIFICADOR, NOME AS CLIENTE FROM tabela_de_clientes;

SELECT * FROM tabela_de_produtos;

SELECT * FROM tabela_de_produtos WHERE 
CODIGO_DO_PRODUTO = '1000889';

SELECT * FROM tabela_de_produtos WHERE 
SABOR = 'Laranja';

SELECT * FROM tabela_de_produtos WHERE 
EMBALAGEM = 'PET';

SELECT * FROM tabela_de_produtos WHERE 
PRECO_DE_LISTA BETWEEN 19.50 AND 19.52;

/*APLICANDO CONSULTAS CONDICIONAIS*/
SELECT * FROM tabela_de_produtos WHERE SABOR = 'MANGA';

SELECT * FROM tabela_de_produtos WHERE 
SABOR = 'MANGA' OR TAMANHO = '470ML';

SELECT * FROM tabela_de_produtos WHERE 
SABOR = 'MANGA' AND TAMANHO = '470ML';

SELECT * FROM tabela_de_produtos WHERE 
NOT(SABOR = 'MANGA' AND TAMANHO = '470ML');

SELECT * FROM tabela_de_produtos WHERE
NOT(SABOR = 'MANGA' OR TAMANHO = '470ML');

SELECT * FROM tabela_de_produtos WHERE 
SABOR = 'MANGA' AND NOT(TAMANHO = '470ML');

SELECT * FROM tabela_de_produtos WHERE 
SABOR IN ('MANGA', 'LARANJA');

SELECT * FROM tabela_de_clientes WHERE 
CIDADE IN ('RIO DE JANEIRO', 'SÃO PAULO') AND IDADE >= 20;

SELECT * FROM tabela_de_clientes WHERE 
CIDADE IN ('RIO DE JANEIRO', 'SÃO PAULO') AND IDADE >= 20;

SELECT * FROM tabela_de_clientes WHERE 
CIDADE IN ('SÃO PAULO', 'RIO DE JANEIRO') AND 
IDADE >= 20 AND IDADE <=22;

/*USANDO O LIKE*/
SELECT * FROM tabela_de_produtos WHERE SABOR LIKE '%MAÇÃ%'
AND EMBALAGEM = 'PET';

SELECT * FROM tabela_de_clientes WHERE NOME LIKE '%MATTOS%';

/*USANDO O DISTINCT PARA VISUALIZAR A TABELA*/
SELECT EMBALAGEM, TAMANHO FROM tabela_de_produtos;

SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos;

SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos
WHERE SABOR = 'LARANJA';

/*EXERCICIO*/
SELECT DISTINCT BAIRRO, CIDADE FROM tabela_de_clientes WHERE CIDADE = 'RIO DE JANEIRO';











 