USE SUCOS;

/*FUNÇÕES DE STRING*/
 SELECT LTRIM('      OLÁ') AS RESULTADO;
 
 SELECT RTRIM('OLÁ      ') AS RESULTADO;
 
 SELECT TRIM(       'OLÁ      ') AS RESULTADO;
 
 SELECT CONCAT('OLÁ', ' ', 'TUDO BEM', '?')AS RESULTADO;
 
 SELECT UPPER('olá tudo bem?') AS RESULTADO;
 
 SELECT SUBSTRING('OLÁ, TUDO BEM?', 6) AS RESULTADO;
 
 SELECT SUBSTRING('OLÁ, TUDO BEM?', 6, 4) AS RESULTADO;
 
 SELECT CONCAT(NOME, ' (', CPF, ' )') AS RESULTADO FROM tabela_de_clientes;
 
 /*EXERCICIO*/
 SELECT CONCAT(NOME, ' (', ENDERECO_1, ' | ', BAIRRO,' | ', 
 CIDADE,' | ', ESTADO, ' )')
 FROM tabela_de_clientes;
 
 /*FUNÇÕES DE DATAS*/
 SELECT CURDATE();
 
 SELECT CURRENT_TIME();
 
 SELECT CURRENT_TIMESTAMP();
 
 SELECT YEAR(CURRENT_TIMESTAMP());
 
 SELECT DAY(CURRENT_TIMESTAMP());
 
 SELECT MONTH(CURRENT_TIMESTAMP());
 
 SELECT MONTHNAME(CURRENT_TIMESTAMP());
 
 SELECT DATEDIFF(CURRENT_TIMESTAMP(), '2019-01-01');
 
 SELECT DATEDIFF(CURRENT_TIMESTAMP(), '2000-04-20');
 
 SELECT DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 DAY) AS RESULTADO;
 
 SELECT DISTINCT DATA_VENDA, 
 DAYNAME(DATA_VENDA) AS DIA, MONTHNAME(DATA_VENDA) AS MES,
 YEAR(DATA_VENDA) AS ANO FROM notas_fiscais;
 
 /*EXERCICIO2*/
 SELECT NOME, TIMESTAMPDIFF(YEAR, DATA_DE_NASCIMENTO, CURDATE()) AS IDADE
 FROM tabela_de_clientes;
 
 /*FUNÇÕES MATEMÁTICAS*/
 SELECT 23+((25-2)/2)*45;
 
 SELECT CEILING(12.333333333) AS RESULTADO; /*ARREDONDA PRA CIMA*/
 
 SELECT ROUND(12.333333333) AS RESULTADO; /*ARREDONDA PRO MAIS PROXIMO*/
 
 SELECT FLOOR(12.333333333) AS RESULTADO; /*ARREDONDA PRA BAIXO*/
 
 SELECT RAND() AS RESULTADO;
 
 SELECT NUMERO, QUANTIDADE, PRECO FROM itens_notas_fiscais;
 
 SELECT NUMERO, QUANTIDADE, PRECO, ROUND(QUANTIDADE * PRECO, 2) AS FATURAMENTO
 FROM itens_notas_fiscais;
 
 /*EXERCICIO2*/
 SELECT YEAR(DATA_VENDA) AS ANO, FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) AS IMPOSTO
 FROM notas_fiscais NF INNER JOIN itens_notas_fiscais INF
 ON NF.NUMERO = INF.NUMERO WHERE YEAR(DATA_VENDA) = 2016
 GROUP BY YEAR(DATA_VENDA);
 
 /*CONVERSÃO DE DADOS*/
 SELECT CURRENT_TIMESTAMP() AS RESULTADO;
 
 SELECT CONCAT('O DIA DE HOJE É: ', CURRENT_TIMESTAMP()) AS RESULTADO;
 
 SELECT CONCAT('A DATA DE HOJE É: ', 
 DATE_FORMAT(CURRENT_TIMESTAMP(), '%m/%y')) AS RESULTADO;
 
 SELECT CONCAT('A DATA DE HOJE É: ', 
 DATE_FORMAT(CURRENT_TIMESTAMP(), '%d/%c/%y')) AS RESULTADO;
 
 SELECT CONCAT('A DATA DE HOJE É: ', 
 DATE_FORMAT(CURRENT_TIMESTAMP(), '%W, %d/%m/%Y')) AS RESULTADO; 
 
 SELECT CONCAT('A DATA DE HOJE É: ', 
 DATE_FORMAT(CURRENT_TIMESTAMP(), '%W, %d/%m/%Y - %U')) AS RESULTADO;
 
 SELECT CONVERT(23.3, CHAR) AS RESULTADO;
 
 /*EXERCICIO FINAL*/
SELECT CONCAT('O cliente ', TC.NOME, ' faturou ', 
CAST(SUM(INF.QUANTIDADE * INF.preco) AS char (20))
 , ' no ano ', CAST(YEAR(NF.DATA_VENDA) AS char (20))) AS SENTENCA FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_clientes TC ON NF.CPF = TC.CPF
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY TC.NOME, YEAR(DATA_VENDA);


 
 
 
 
 
 
 