USE SUCOS;

UPDATE TBVENDEDORES
SET PERCENTUAL_COMISSAO = 0.11
WHERE MATRICULA = '00236';

UPDATE TBVENDEDORES
SET NOME = 'José Geraldo da Fonseca Junior'
WHERE MATRICULA = '00233';

SELECT * FROM tbvendedores;