USE SUCOS;

/*RELATÓRIO DE VENDAS VÁLIDAS*/
SELECT * FROM itens_notas_fiscais;

SELECT * FROM notas_fiscais;

/*CONSULTAS COM VENDAS DE CLIENTES PRO MES*/
SELECT NF.CPF, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO, 
SUM(INF.QUANTIDADE) AS QTD_VENDAS FROM notas_fiscais NF 
INNER JOIN itens_notas_fiscais INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m');

/*LIMITE DE COMPRA POR CLIENTE*/
SELECT TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA AS QUANTIDADE_LIMITE
FROM tabela_de_clientes TC;

SELECT X.CPF, X.NOME, X.MES_ANO, X.QTD_VENDAS, X.QUANTIDADE_LIMITE,
CASE WHEN (X.QUANTIDADE_LIMITE - X.QTD_VENDAS) < 0 THEN 'INVÁLIDO'
ELSE 'VÁLIDO'
END AS STATUS_VENDA
FROM(
SELECT NF.CPF,TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO, 
SUM(INF.QUANTIDADE) AS QTD_VENDAS, MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE 
FROM notas_fiscais NF 
INNER JOIN itens_notas_fiscais INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_clientes TC
ON TC.CPF = NF.CPF
GROUP BY NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m')) X;

/*EXERCICIO*/
SELECT X.CPF, X.NOME, X.MES_ANO, X.QTD_VENDAS, X.QUANTIDADE_LIMITE,
(1-(X.QUANTIDADE_LIMITE / X.QTD_VENDAS) * 100) AS PERCENTUAL,
CASE WHEN (X.QUANTIDADE_LIMITE - X.QTD_VENDAS) < 0 THEN 'INVÁLIDO'
ELSE 'VÁLIDO'
END AS STATUS_VENDA
FROM(
SELECT NF.CPF,TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO, 
SUM(INF.QUANTIDADE) AS QTD_VENDAS, MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE 
FROM notas_fiscais NF 
INNER JOIN itens_notas_fiscais INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_clientes TC
ON TC.CPF = NF.CPF
GROUP BY NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m')) X
WHERE (X.QUANTIDADE_LIMITE - X.QTD_VENDAS) < 0;

/*RELATÓRIO DE VENDAS POR SABOR*/
 SELECT TP.SABOR, NF.DATA_VENDA, INF.QUANTIDADE FROM tabela_de_produtos TP 
 INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
 INNER JOIN notas_fiscais NF ON NF.NUMERO = INF.NUMERO;
 
 /*QUANTIDADE POR SABOR*/
 SELECT X.SABOR, X.ANO, X.QTD, X.TAMANHO FROM(
 SELECT TP.SABOR, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QTD FROM tabela_de_produtos TP 
 INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
 INNER JOIN notas_fiscais NF ON NF.NUMERO = INF.NUMERO
 WHERE YEAR(NF.DATA_VENDA) = 2016
 GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)
 ORDER BY SUM(INF.QUANTIDADE) DESC) X;
 
 /*QUANTIDADE TOTAL*/
 SELECT X.ANO, X.QTD FROM(
 SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QTD FROM tabela_de_produtos TP 
 INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
 INNER JOIN notas_fiscais NF ON NF.NUMERO = INF.NUMERO
 WHERE YEAR(NF.DATA_VENDA) = 2016
 GROUP BY YEAR(NF.DATA_VENDA)
 ORDER BY SUM(INF.QUANTIDADE) DESC) X;
 
 SELECT * FROM
 (SELECT TP.SABOR, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QTD FROM tabela_de_produtos TP 
 INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
 INNER JOIN notas_fiscais NF ON NF.NUMERO = INF.NUMERO
 WHERE YEAR(NF.DATA_VENDA) = 2016
 GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)) AS VENDA_SABOR
 INNER JOIN 
 (SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QTD FROM tabela_de_produtos TP 
 INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
 INNER JOIN notas_fiscais NF ON NF.NUMERO = INF.NUMERO
 WHERE YEAR(NF.DATA_VENDA) = 2016
 GROUP BY YEAR(NF.DATA_VENDA)) AS VENDA_TOTAL
 ON VENDA_SABOR.ANO = VENDA_TOTAL.ANO;
 
 SELECT VENDA_SABOR.SABOR, VENDA_SABOR.ANO, VENDA_SABOR.QTD,
 ((VENDA_SABOR.QTD / VENDA_TOTAL.QTD) * 100) AS PARTICIPACAO FROM
 (SELECT TP.SABOR, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QTD FROM tabela_de_produtos TP 
 INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
 INNER JOIN notas_fiscais NF ON NF.NUMERO = INF.NUMERO
 WHERE YEAR(NF.DATA_VENDA) = 2016
 GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)) AS VENDA_SABOR
 INNER JOIN 
 (SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QTD FROM tabela_de_produtos TP 
 INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
 INNER JOIN notas_fiscais NF ON NF.NUMERO = INF.NUMERO
 WHERE YEAR(NF.DATA_VENDA) = 2016
 GROUP BY YEAR(NF.DATA_VENDA)) AS VENDA_TOTAL
 ON VENDA_SABOR.ANO = VENDA_TOTAL.ANO
 ORDER BY VENDA_SABOR.QTD DESC;
 
 /*EXERCICIO*/
 SELECT VENDA_TAMANHO.TAMANHO, VENDA_TAMANHO.ANO, VENDA_TAMANHO.QTD,
 ((VENDA_TAMANHO.QTD / VENDA_TOTAL.QTD) * 100) AS PARTICIPACAO FROM
 (SELECT TP.TAMANHO, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QTD FROM tabela_de_produtos TP 
 INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
 INNER JOIN notas_fiscais NF ON NF.NUMERO = INF.NUMERO
 WHERE YEAR(NF.DATA_VENDA) = 2016
 GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)) AS VENDA_TAMANHO
 INNER JOIN 
 (SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QTD FROM tabela_de_produtos TP 
 INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
 INNER JOIN notas_fiscais NF ON NF.NUMERO = INF.NUMERO
 WHERE YEAR(NF.DATA_VENDA) = 2016
 GROUP BY YEAR(NF.DATA_VENDA)) AS VENDA_TOTAL
 ON VENDA_TAMANHO.ANO = VENDA_TOTAL.ANO
 ORDER BY VENDA_TAMANHO.QTD DESC;
